AGKOZAK_PROMPT_CHAR=''
AGKOZAK_USER_HOST_DISPLAY=0
AGKOZAK_MULTILINE=0
AGKOZAK_CMD_EXEC_TIME=0

AGKOZAK_CUSTOM_PROMPT+='%F{cyan}%2v%f%b'
# Virtual environment indicator
AGKOZAK_CUSTOM_PROMPT+=' %(10V.%F{green}[%10v] %f.)'
