
# rust
export PATH="$HOME/.cargo/bin:$PATH"

# add rtags path
export PATH="$PATH:~/.emacs.d/.local/etc/rtags/rtags-2.20/bin"

# change language to english
export LANG="en_US.UTF-8"

# editor
export EDITOR=nvim
export VISUAL=nvim
export VIMRC=~/.config/nvim/init.vim

# Customize to your needs...
export KEYTIMEOUT=1

# fix man page wrapping
export MANWIDTH=60

# -S disable line wrapping
# -R displays ANSI color escape sequences in "raw" form
export LESS="-S -R"

# remove path duplicates
typeset -aU path
