# rust
export PATH="$HOME/.cargo/bin:$PATH"

# pip
export PATH="$HOME/Library/Python/3.7/bin:$PATH"

# chrome
export PATH="$HOME/chrome-control:$PATH"

# doom
export PATH="$HOME/.emacs.d/bin:$PATH"

# texinfo
export PATH="/usr/local/opt/texinfo/bin:$PATH"

# add rtags path
export PATH="$PATH:~/.emacs.d/.local/etc/rtags/rtags-2.20/bin"

# change language to english
export LANG="en_US.UTF-8"

# editor
export EDITOR=nvim
export VISUAL=nvim
export VIMRC=~/.config/nvim/init.vim

# Customize to your needs...
export KEYTIMEOUT=1

# fix man page wrapping
export MANWIDTH=60

# -S disable line wrapping
# -R displays ANSI color escape sequences in "raw" form
export LESS="-S -R"

# remove path duplicates
typeset -aU path

# terminal
export TERMINAL='kitty'
export UBER_SECUREVAULT_ROLE=dev

# go monorepo
#export MONOREPO_GOPATH_MODE=1
#export "GOPATH=$HOME/go-code"
#export "PATH=$GOPATH/bin:$HOME/go-code/tools:$PATH"

# go
export GOPATH="$HOME/gocode"
export PATH="$HOME/gocode/bin:$PATH"
#export PATH="/usr/local/bin:$GOPATH"

# hailstorm
export PATH="/usr/local/opt/curl-openssl/bin:$PATH"

# uber
export PATH="/opt/uber/bin/:$PATH"
